# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: photocap.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ephotocap.proto\"u\n\x07Message\x12\r\n\x05phone\x18\x01 \x01(\x04\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x0f\n\x07\x61\x62onent\x18\x03 \x01(\t\x12\x0b\n\x03lac\x18\x04 \x01(\x04\x12\x0c\n\x04\x63\x65ll\x18\x05 \x01(\x04\x12\x0e\n\x06\x61zimut\x18\x06 \x01(\x04\x12\x12\n\nbs_address\x18\x07 \x01(\t\")\n\x0eIsSuccessfully\x12\x17\n\x0fis_successfully\x18\x01 \x01(\x08\x32;\n\rMsTelegramBot\x12*\n\x0bSendMessage\x12\x08.Message\x1a\x0f.IsSuccessfully\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'photocap_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGE']._serialized_start=18
  _globals['_MESSAGE']._serialized_end=135
  _globals['_ISSUCCESSFULLY']._serialized_start=137
  _globals['_ISSUCCESSFULLY']._serialized_end=178
  _globals['_MSTELEGRAMBOT']._serialized_start=180
  _globals['_MSTELEGRAMBOT']._serialized_end=239
# @@protoc_insertion_point(module_scope)
